# Generated by Django 5.2.1 on 2025-06-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_lb", "0002_filme_genero_serie_remove_usuario_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuario",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="Senha",
            new_name="senha",
        ),
        migrations.RemoveField(
            model_name="obra",
            name="genero",
        ),
    ]
